### ISSUE TITLE
My Code/step3.py job is failing

### ISSUE THREAD

**Issue by iconix** [Azure/MachineLearningSamples-DocumentCollectionAnalysis#4]
Hello, I'm walking through the provided [tutorial](https://docs.microsoft.com/en-us/azure/machine-learning/preview/scenario-document-collection-analysis) using Azure Machine Learning Workbench. In my DocumentCollectionAnalysis jobs so far, `Code/step1.py` and `Code/step2.py` completed successfully. However, `Code/step3.py` fails (attempted twice).

![image](https://user-images.githubusercontent.com/1144401/31204859-b7fa480a-a922-11e7-9193-9463af459e0d.png)

The error info does not reveal much to me:
`Running: ['python', 'azureml-setup/run_script.py', 'python', 'azureml-setup/history_injector.py', 'Code/step3.py']
Traceback (most recent call last):
  File "azureml-setup/run_script.py", line 113, in <module>
    invoke()
  File "azureml-setup/run_script.py", line 39, in invoke
    subprocess.check_call(sys.argv[1:], stdout=file, stderr=file)    
  File "C:\Users\narho\AppData\local\AmlWorkbench\Python\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'azureml-setup/history_injector.py', 'Code/step3.py']' returned non-zero exit status 1`

How can I go about debugging the issue? Thanks.

**Comment by iconix** [comment]
Discovered that the "Job Title" (e.g., `Code/step3.py [4]` in the image originally posted) is click-able, and under `Log Files`, the `driver_log` provides more detail for debugging.

**Comment by ozonemojo2** [comment]
I got the same error. How to solve it?

This the LOG
`Warning: Required AzureML dependencies were not found.
Certain AzureML functionality will not be available.
Run the following commands to install them:
  pip install -I --index-url https://azuremldownloads.azureedge.net/python-repository/preview --extra-index-url https://pypi.python.org/simple azureml-requirements

Running: ['python', 'azureml-setup/run_script.py', 'python', 'azureml-setup/history_injector.py', 'Code/step3.py']
<urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>
Traceback (most recent call last):
  File "azureml-setup/run_script.py", line 158, in <module>
    invoke()
  File "azureml-setup/run_script.py", line 43, in invoke
    subprocess.check_call(sys.argv[1:], stdout=file, stderr=file)
  File "C:\Users\andre\AppData\local\AmlWorkbench\Python\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'azureml-setup/history_injector.py', 'Code/step3.py']' returned non-zero exit status 1


Logging experiment failure in history service.
Uploading experiment status to history service.
`

**Comment by payalgaikwad42** [comment]
i am getting this error
Running: ['python', 'azureml-setup/run_script.py', 'python', 'azureml-setup/history_injector.py', 'iot_score.py']
<urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>
Traceback (most recent call last):
  File "azureml-setup/run_script.py", line 158, in <module>
    invoke()
  File "azureml-setup/run_script.py", line 43, in invoke
    subprocess.check_call(sys.argv[1:], stdout=file, stderr=file)
  File "C:\Users\payal\AppData\local\AmlWorkbench\Python\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'azureml-setup/history_injector.py', 'iot_score.py']' returned non-zero exit status 1


Logging experiment failure in history service.
Uploading experiment status to history service.
